// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNhI3r_-SIhWsYmDXUAXmII7NcRxolh0I',
    appId: '1:668519807707:web:db2f7384c0b55ea3a5eafe',
    messagingSenderId: '668519807707',
    projectId: 'chat-app-85428',
    authDomain: 'chat-app-85428.firebaseapp.com',
    storageBucket: 'chat-app-85428.appspot.com',
    measurementId: 'G-EG7WKFB1ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3bDLUgM_NDO4iUJ7mzcoX1EwsX-Tx5qE',
    appId: '1:668519807707:android:4cdf17f5c484d3bba5eafe',
    messagingSenderId: '668519807707',
    projectId: 'chat-app-85428',
    storageBucket: 'chat-app-85428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfKZwMqUUCen2p7dmM4AkzEtjz4v29Vi8',
    appId: '1:668519807707:ios:3f7417e5a0f5345ba5eafe',
    messagingSenderId: '668519807707',
    projectId: 'chat-app-85428',
    storageBucket: 'chat-app-85428.appspot.com',
    iosBundleId: 'com.example.projectChat',
  );
}
